name: Build the frontend project

on:
  push:
    branches:
    - main
    - release/*
  
jobs:
  buildWebsite:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.x'
          
      - uses: actions/checkout@v4  

      - name: Install Dependencies
        run: npm install


